[package]
name = "sentinel-malware"
version.workspace = true
edition.workspace = true

[dependencies]
sentinel-core = { workspace = true }
sentinel-endpoint = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
bytes = { workspace = true }
byteorder = { workspace = true }
parking_lot = { workspace = true }
dashmap = { workspace = true }
notify = { workspace = true }
reqwest = { workspace = true }
regex = { workspace = true }
aho-corasick = { workspace = true }
sysinfo = { workspace = true }
nix = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }
glob = { workspace = true }
blake3 = { workspace = true }
xxhash-rust = { workspace = true }
flate2 = { workspace = true }
lz4_flex = { workspace = true }
memmap2 = { workspace = true }
crossbeam = { workspace = true }
libc = "0.2"
dirs-next = "2.0"
